# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='media/banner/%Y/%m', verbose_name='轮播图'),
        ),
    ]
