# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='校区')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '校区',
                'verbose_name_plural': '校区',
            },
        ),
        migrations.CreateModel(
            name='CourseCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学院名称')),
                ('desc', models.TextField(verbose_name='学院描述')),
                ('tag', models.CharField(default='世界闻名', max_length=10, verbose_name='学院标签')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('image', models.ImageField(upload_to='college/%Y/%m', verbose_name='logo')),
                ('address', models.CharField(max_length=150, verbose_name='学院地址')),
                ('student_nums', models.IntegerField(default=0, verbose_name='学习人数')),
                ('courses_nums', models.IntegerField(default=0, verbose_name='课程数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cau_college.Campus', verbose_name='所在校区')),
            ],
            options={
                'verbose_name': '课程学院',
                'verbose_name_plural': '课程学院',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='教师名称')),
                ('work_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('work_position', models.CharField(max_length=50, verbose_name='教师职位')),
                ('points', models.CharField(max_length=50, verbose_name='教学特点')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('age', models.IntegerField(default=18, verbose_name='教师年龄')),
                ('image', models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='头像')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cau_college.CourseCollege', verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
    ]
