# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cau_college', '0002_auto_20170426_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='media/teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
