# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cau_college', '0003_auto_20170426_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecollege',
            name='image',
            field=models.ImageField(upload_to='media/college/%Y/%m', verbose_name='logo'),
        ),
    ]
