# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cau_college', '0007_auto_20170426_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecollege',
            name='campus',
            field=models.CharField(choices=[('dxq', '东校区'), ('xxq', '西校区'), ('ytxq', '烟台校区')], default='dxq', max_length=20, verbose_name='校区'),
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
    ]
