# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cau_college', '0008_auto_20170426_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecollege',
            old_name='courses_nums',
            new_name='course_nums',
        ),
    ]
