# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cau_college', '0009_auto_20170427_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecollege',
            name='image',
            field=models.ImageField(upload_to='college/%Y/%m', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
