# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='image',
            field=models.ImageField(default='media/image/default.png', upload_to='media/image/%Y/%m', verbose_name='头像'),
        ),
    ]
