# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_member', '0002_auto_20170426_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='image',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='头像'),
        ),
    ]
