# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cau_college', '0001_initial'),
        ('mooc_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cau_college.CourseCollege', verbose_name='课程机构'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cau_college.Teacher', verbose_name='讲师'),
        ),
    ]
