# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mooc_course', '0002_auto_20170425_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='media/course/%Y/%m', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(upload_to='media/course/resource/%Y/%m', verbose_name='资源文件'),
        ),
    ]
