# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cau_college', '0008_auto_20170426_1914'),
        ('mooc_course', '0003_auto_20170426_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_org',
        ),
        migrations.AddField(
            model_name='course',
            name='course_college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cau_college.CourseCollege', verbose_name='课程学院'),
        ),
    ]
